export const BRAND = {
  name: "Momofy",
  tagline: "India's Fastest Growing Momo Franchise",
  phone: process.env.NEXT_PUBLIC_PHONE ?? "916305468471",
  waNumber: process.env.NEXT_PUBLIC_WA_NUMBER ?? "916305468471",
  email: process.env.NEXT_PUBLIC_EMAIL ?? "hello@momofyy.com",
  address: "Bangalore, Karnataka, India",
};

export const WA_NUMBER = process.env.NEXT_PUBLIC_WA_NUMBER ?? "916305468471";

export const PRODUCTS = [
  {
    id: "veg-momos",
    slug: "veg-momos",
    name: "Veg Momos",
    emoji: "🥟",
    image: "https://i.ibb.co/nRtqDBQ/453840738-1025498032507049-8655357820299598527-n-min.jpg",
    gradient: "from-emerald-400 to-green-600",
    weight: "25 pcs | 500g",
    tag: "Bestseller",
    tagColor: "bg-[#E8320A] text-white",
    price: 99,
    mrp: 300,
    unit: "packet",
    margin: "67%",
    moq: "Min 30 packs",
    desc: "Made with farm-fresh Ooty cabbage, carrots, and onions using AI-based machines for ultra-thin dough and authentic taste.",
    ingredients: [
      "Ooty Cabbage", "Fresh Carrots", "Onions", "Premium Maida",
      "Sunpure Oil", "Aromat Seasoning", "Green Chillies", "Coriander",
    ],
    nutrition: { calories: 210, protein: "6g", carbs: "32g", fat: "7g", serving: "5 pieces (100g)" },
    storage: "Store at -18°C in a deep freezer only. Do not refreeze after thawing.",
    steamInstructions: "Steam for 5–8 minutes after water is hot. Cook directly from the freezer. Use a silicone momo net lightly oiled to prevent sticking.",
  },
  {
    id: "chicken-momos",
    slug: "chicken-momos",
    name: "Chicken Momos",
    emoji: "🍗",
    image: "https://i.ibb.co/2htCf1N/Whats-App-Image-2024-11-03-at-17-17-12.jpg",
    gradient: "from-orange-400 to-red-500",
    weight: "25 pcs | 500g",
    tag: "High Margin",
    tagColor: "bg-[#FFB347] text-[#1A0A00]",
    price: 129,
    mrp: 350,
    unit: "packet",
    margin: "63%",
    moq: "Min 30 packs",
    desc: "100% real chicken and fresh onions, crafted using AI-based machines for the perfect balance of flavor and texture.",
    ingredients: [
      "Fresh Chicken (100% real)", "Onions", "Premium Maida",
      "Sunpure Oil", "Aromat Seasoning", "Ginger", "Garlic", "Black Pepper",
    ],
    nutrition: { calories: 250, protein: "14g", carbs: "28g", fat: "10g", serving: "5 pieces (100g)" },
    storage: "Store at -18°C in a deep freezer only. Do not refreeze after thawing.",
    steamInstructions: "Steam for 5–8 minutes after water is hot. Cook directly from the freezer. Use a silicone momo net lightly oiled to prevent sticking.",
  },
  {
    id: "paneer-momos",
    slug: "paneer-momos",
    name: "Paneer Momos",
    emoji: "🧀",
    image: "https://i.ibb.co/wgp04pq/461141402-1251023039233117-8189497260763456489-n.jpg",
    gradient: "from-yellow-300 to-amber-500",
    weight: "25 pcs | 500g",
    tag: "Fan Favourite",
    tagColor: "bg-purple-600 text-white",
    price: 129,
    mrp: 400,
    unit: "packet",
    margin: "68%",
    moq: "Min 30 packs",
    desc: "Premium Milkymist Paneer and fresh onions in ultra-thin dough, ensuring a rich and creamy filling every time.",
    ingredients: [
      "Milkymist Paneer", "Onions", "Bell Peppers", "Premium Maida",
      "Sunpure Oil", "Aromat Seasoning", "Green Chillies", "Coriander",
    ],
    nutrition: { calories: 240, protein: "10g", carbs: "30g", fat: "9g", serving: "5 pieces (100g)" },
    storage: "Store at -18°C in a deep freezer only. Do not refreeze after thawing.",
    steamInstructions: "Steam for 5–8 minutes after water is hot. Cook directly from the freezer. Use a silicone momo net lightly oiled to prevent sticking.",
  },
  {
    id: "mix-veg-momos",
    slug: "mix-veg-momos",
    name: "Mix Veg Momos",
    emoji: "🥦",
    image: "https://i.ibb.co/8KPJcw4/heroimg1-1.jpg",
    gradient: "from-lime-400 to-emerald-500",
    weight: "25 pcs | 500g",
    tag: "Wholesome",
    tagColor: "bg-green-600 text-white",
    price: 123,
    mrp: 299,
    unit: "packet",
    margin: "59%",
    moq: "Min 30 packs",
    desc: "Fresh cauliflower, carrots, beans, and sweet corn — a wholesome, flavorful filling inside delicate thin dough.",
    ingredients: [
      "Cauliflower", "Carrots", "Beans", "Sweet Corn", "Onions",
      "Premium Maida", "Sunpure Oil", "Aromat Seasoning",
    ],
    nutrition: { calories: 195, protein: "5g", carbs: "34g", fat: "6g", serving: "5 pieces (100g)" },
    storage: "Store at -18°C in a deep freezer only. Do not refreeze after thawing.",
    steamInstructions: "Steam for 5–8 minutes after water is hot. Cook directly from the freezer. Use a silicone momo net lightly oiled to prevent sticking.",
  },
  {
    id: "corn-cheese-momos",
    slug: "corn-cheese-momos",
    name: "Corn Cheese Momos",
    emoji: "🌽",
    image: "https://i.ibb.co/bdxYFMw/453608848-1018505036534082-7988940111034472837-n.jpg",
    gradient: "from-yellow-300 to-orange-400",
    weight: "25 pcs | 500g",
    tag: "Premium",
    tagColor: "bg-orange-500 text-white",
    price: 149,
    mrp: 500,
    unit: "packet",
    margin: "70%",
    moq: "Min 30 packs",
    desc: "Creamy Amul cheese and American sweet corn in a soft ultra-thin wrapper — gooey and indulgent.",
    ingredients: [
      "American Sweet Corn", "Amul Cheese", "Onions", "Premium Maida",
      "Sunpure Oil", "Mixed Herbs", "Black Pepper", "Aromat Seasoning",
    ],
    nutrition: { calories: 270, protein: "8g", carbs: "35g", fat: "11g", serving: "5 pieces (100g)" },
    storage: "Store at -18°C in a deep freezer only. Do not refreeze after thawing.",
    steamInstructions: "Steam for 5–8 minutes after water is hot. Cook directly from the freezer. Use a silicone momo net lightly oiled to prevent sticking.",
  },
  {
    id: "premium-momo-chutney",
    slug: "premium-momo-chutney",
    name: "Premium Momo Chutney",
    emoji: "🌶️",
    image: "https://i.ibb.co/VjNjmqF/461829466-405777669008962-2506022850992959093-n-1-1.jpg",
    gradient: "from-red-500 to-rose-600",
    weight: "per packet",
    tag: "New",
    tagColor: "bg-blue-600 text-white",
    price: 179,
    mrp: 275,
    unit: "packet",
    margin: "35%",
    moq: "Min 20 packs",
    desc: "Spicy and tangy dip made with the finest ingredients. Ideal for all momo types. Available in bulk for cafes and restaurants.",
    ingredients: [
      "Tomatoes", "Red Chillies", "Garlic", "Ginger",
      "Onions", "Vinegar", "Salt", "Spice Blend",
    ],
    nutrition: { calories: 45, protein: "1g", carbs: "9g", fat: "1g", serving: "30g (1 tbsp)" },
    storage: "Store at -18°C or refrigerate after opening. Best consumed within 7 days of opening.",
    steamInstructions: "Thaw at room temperature for 30 minutes before serving. Stir well before use.",
  },
  {
    id: "family-pack",
    slug: "family-pack",
    name: "Momofy Family Pack",
    emoji: "🎁",
    image: "https://i.ibb.co/nRtqDBQ/453840738-1025498032507049-8655357820299598527-n-min.jpg",
    gradient: "from-pink-400 to-rose-500",
    weight: "18 items combo",
    tag: "Best Value",
    tagColor: "bg-pink-600 text-white",
    price: 1799,
    mrp: 2499,
    unit: "combo",
    margin: "40%",
    moq: "Min 1 combo",
    desc: "Everything you need for a perfect momo night — 5 packs each of Veg, Chicken & Paneer momos, 2 spicy momo chutneys, and creamy mayo. Best value combo.",
    ingredients: [
      "5× Veg Momos (25 pcs each)",
      "5× Chicken Momos (25 pcs each)",
      "5× Paneer Momos (25 pcs each)",
      "2× Premium Momo Chutney",
      "1× Creamy Mayonnaise",
    ],
    nutrition: { calories: 230, protein: "9g", carbs: "30g", fat: "9g", serving: "5 pieces (100g avg)" },
    storage: "Store all items at -18°C in a deep freezer. Do not refreeze after thawing.",
    steamInstructions: "Steam momos 5–8 minutes directly from frozen. Thaw chutney and mayo 30 min before serving.",
  },
  {
    id: "chicken-strips",
    slug: "chicken-strips",
    name: "Chicken Strips",
    emoji: "🍖",
    image: "https://i.ibb.co/tPz68wSS/Chicken-Strips-2.jpg",
    gradient: "from-amber-400 to-orange-600",
    weight: "1kg",
    tag: "KFC-Style",
    tagColor: "bg-red-700 text-white",
    price: 299,
    mrp: 399,
    unit: "kg",
    margin: "25%",
    moq: "Min 20 packs",
    desc: "KFC-style crispy chicken strips with premium chicken and signature spice blend. Perfect for restaurants, cafés, and fast-food businesses.",
    ingredients: [
      "Premium Chicken Breast", "Signature Spice Blend", "Maida", "Corn Flour",
      "Baking Powder", "Sunpure Oil", "Garlic Powder", "Paprika",
    ],
    nutrition: { calories: 310, protein: "22g", carbs: "18g", fat: "16g", serving: "100g" },
    storage: "Store at -18°C in a deep freezer only. Do not refreeze after thawing.",
    steamInstructions: "Deep fry at 180°C for 4–6 minutes directly from frozen until golden. Or air fry at 200°C for 8–10 minutes.",
  },
];

export const WHY_CARDS = [
  {
    icon: "🏭",
    title: "Direct from Factory",
    desc: "No middlemen. You buy directly from our Bangalore facility at factory prices.",
  },
  {
    icon: "🏷️",
    title: "Private Labeling",
    desc: "Launch your own brand. We manufacture, you brand. White-label ready.",
  },
  {
    icon: "🚚",
    title: "Fast Delivery",
    desc: "2-day delivery across Bangalore. Order by WhatsApp and we'll confirm the slot.",
  },
  {
    icon: "🤝",
    title: "Distribution Network",
    desc: "Become an exclusive distributor in your city. 11.11% guaranteed margin.",
  },
  {
    icon: "📱",
    title: "Zomato & Swiggy Ready",
    desc: "Products are cloud-kitchen optimised with listing support included.",
  },
  {
    icon: "🌿",
    title: "No Preservatives",
    desc: "100% natural ingredients. Flash-frozen at source. No artificial additives.",
  },
];

export const STATS = [
  { label: "Restaurants Supplied", value: "2,400+" },
  { label: "Pieces Per Day", value: "40,000" },
  { label: "Quality Assured", value: "✓" },
  { label: "In Business Since", value: "2022" },
  { label: "Delivery Coverage", value: "Bangalore" },
];

export const B2B_CARDS = [
  {
    icon: "🍽️",
    title: "Restaurant & Café Supply",
    desc: "Bulk frozen momo supply with consistent quality. MOQ ₹3,000. 2-day delivery across Bangalore.",
  },
  {
    icon: "📦",
    title: "Distributorship",
    desc: "Become Momofy's city distributor. 11.11% guaranteed margin on every order. Exclusive territory rights available.",
  },
  {
    icon: "🏷️",
    title: "Private Labeling",
    desc: "Launch your own momo brand. We handle manufacturing, packaging, and compliance. You handle sales.",
  },
  {
    icon: "✈️",
    title: "Export",
    desc: "We supply to Indian restaurants globally. Food safety documentation provided.",
  },
];

export const TESTIMONIALS = [
  {
    name: "Rajesh Nair",
    role: "Restaurant Owner",
    city: "Bangalore",
    text: "Momofy's frozen momos have been a game-changer. Consistent quality, on-time delivery, and our customers can't stop ordering more. Highly recommended for any restaurant owner.",
    rating: 5,
    avatar: "RN",
    color: "bg-[#E8320A]",
  },
  {
    name: "Aishwarya Menon",
    role: "Café Owner",
    city: "Chennai",
    text: "The paneer and corn cheese variants are absolute hits at our café. Pricing is the most competitive we've found. Reliable partner for over a year now.",
    rating: 5,
    avatar: "AM",
    color: "bg-purple-600",
  },
  {
    name: "Vinod Kumar",
    role: "Distributor",
    city: "Hyderabad",
    text: "As a distributor, trust is everything. Momofy delivers on quality, margin, and timelines every single time. The 11.11% margin is real and consistent.",
    rating: 5,
    avatar: "VK",
    color: "bg-green-600",
  },
  {
    name: "Priya Sharma",
    role: "Cloud Kitchen Owner",
    city: "Pune",
    text: "We launched our momo cloud kitchen with Momofy and broke even in 6 weeks. The setup support and Zomato onboarding help made all the difference.",
    rating: 5,
    avatar: "PS",
    color: "bg-[#FFB347] text-[#1A0A00]",
  },
  {
    name: "Arjun Patel",
    role: "Food Truck Owner",
    city: "Ahmedabad",
    text: "Started with a small order of ₹3,000. Now I order ₹40,000 a month. The quality consistency is what keeps me coming back. No compromise on taste.",
    rating: 5,
    avatar: "AP",
    color: "bg-blue-600",
  },
  {
    name: "Kavitha Reddy",
    role: "Canteen Contractor",
    city: "Bengaluru",
    text: "Supplying to 3 corporate canteens with Momofy products. Employees love the veg momos. Fresh, hygienic, and no complaints in 8 months of service.",
    rating: 5,
    avatar: "KR",
    color: "bg-teal-600",
  },
];

export const FAQS = [
  {
    q: "How long can I store Momofy frozen momos?",
    a: "Up to 3 months at -18°C in a deep freezer. Do not store in a regular refrigerator.",
  },
  {
    q: "How soon is delivery after ordering?",
    a: "Within 2 days of placing the order for most major cities.",
  },
  {
    q: "Are the momos fresh or frozen?",
    a: "Made fresh, then immediately flash-frozen at -18°C to lock in taste, texture, and nutrition.",
  },
  {
    q: "What is the Minimum Order Quantity (MOQ)?",
    a: "₹3,000 minimum order value. Formula: Transport Charges ÷ 30 = MOQ packets.",
  },
  {
    q: "How do I steam Momofy momos correctly?",
    a: "Steam for 5–8 minutes after water is hot, directly from the freezer. Use a silicone momo net with light oil to prevent sticking.",
  },
  {
    q: "Can Momofy momos be fried?",
    a: "Yes! Steam for 4–6 minutes first, then shallow or deep fry for a crunchy golden outer layer.",
  },
  {
    q: "What sauces go well with them?",
    a: "Best with Momofy's own spicy momo chutney and mayo. Both available for bulk order.",
  },
  {
    q: "Do you offer private labeling?",
    a: "Yes. We manufacture and pack — you put your brand on it. Contact us on WhatsApp to get started.",
  },
  {
    q: "Is GST charged on orders?",
    a: "Momofy is under GST Composition Scheme — no GST is charged on B2B sales. Distributors add applicable GST to their end customers.",
  },
  {
    q: "What if I receive a damaged product?",
    a: "Report within 4 hours of delivery with photos on WhatsApp. We resolve all claims promptly.",
  },
];

export const COMPARISON_TABLE = [
  { criteria: "Hygiene Control", fresh: "Variable, exposed to environment", momofy: "Factory processed, sealed & traceable" },
  { criteria: "Preservation", fresh: "Short shelf-life, spoilage risk", momofy: "Flash frozen, long shelf-life without chemicals" },
  { criteria: "Nutrition", fresh: "Can degrade over time", momofy: "Locked-in nutrients via rapid freezing" },
  { criteria: "Consistency", fresh: "Depends on maker", momofy: "Standardized recipe & QC" },
  { criteria: "Convenience", fresh: "Prep time required", momofy: "Steam & serve in minutes" },
];

export const INGREDIENTS = [
  { icon: "🌾", name: "Premium Maida", source: "Sourced from APMC, Yeshwantpura" },
  { icon: "🫙", name: "Quality Oils", source: "Sunpure Oil and Vanaspati" },
  { icon: "🥬", name: "Fresh Produce", source: "Onions & vegetables from APMC" },
  { icon: "🧂", name: "Natural Seasoning", source: "Aromat powder, no MSG" },
  { icon: "🍗", name: "Fresh Chicken", source: "Trusted vendor, freshly cut daily" },
  { icon: "🧀", name: "Premium Paneer", source: "Milkymist — well-known brand" },
];

export const FRANCHISE_STEPS = [
  { step: "01", title: "Apply Online", desc: "Fill the enquiry form. Our team calls within 24 hours." },
  { step: "02", title: "Pay & Confirm", desc: "One-time franchise fee of ₹89,000. Fully documented." },
  { step: "03", title: "Setup & Train", desc: "Equipment, recipes, SOPs, and 3-day hands-on training." },
  { step: "04", title: "Launch & Earn", desc: "Go live with marketing support. Profit from day one." },
];

export const FRANCHISE_FEATURES = [
  "Complete recipe & SOP manual",
  "Branded packaging & signage",
  "Zomato/Swiggy listing support",
  "WhatsApp marketing templates",
  "Dedicated relationship manager",
  "Ongoing product R&D access",
];

export const BULK_PRICING = [
  { qty: "30–99 packs", veg: "₹99", chicken: "₹129", paneer: "₹129" },
  { qty: "100–299 packs", veg: "₹90", chicken: "₹118", paneer: "₹118" },
  { qty: "300–999 packs", veg: "₹82", chicken: "₹109", paneer: "₹109" },
  { qty: "1000+ packs", veg: "₹75", chicken: "₹99", paneer: "₹99" },
];
